<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OtpHarbor.IconPackBuilder</AssemblyName>
    <RootNamespace>OtpHarbor.IconPackBuilder</RootNamespace>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Legends/otp-harbor-icon-pack-builder</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\mappings\*.json" LogicalName="OtpHarbor.IconPackBuilder.Mappings.%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OtpHarbor.IconPackBuilder.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="5.2.3" />
  </ItemGroup>
</Project>
